<?php
class Initial extends CakeMigration {

/**
 * Migration description
 *
 * @var string
 */
	public $description = 'Initial';

/**
 * Actions to be performed
 *
 * @var array $migration
 */
	public $migration = array(
		'up' => array(
			'create_table' => array(
				'api_accesses' => array(
					'id' => array('type' => 'integer', 'null' => false, 'default' => null, 'unsigned' => false, 'key' => 'primary'),
					'user_id' => array('type' => 'integer', 'null' => false, 'default' => null, 'unsigned' => false),
					'token' => array('type' => 'string', 'null' => false, 'default' => null, 'collate' => 'utf8_general_ci', 'charset' => 'utf8'),
					'created' => array('type' => 'timestamp', 'null' => true, 'default' => null),
					'indexes' => array(
						'PRIMARY' => array('column' => 'id', 'unique' => 1),
					),
					'tableParameters' => array('charset' => 'utf8', 'collate' => 'utf8_general_ci', 'engine' => 'InnoDB'),
				),
				'article_events' => array(
					'id' => array('type' => 'biginteger', 'null' => false, 'default' => null, 'unsigned' => false, 'key' => 'primary'),
					'created' => array('type' => 'timestamp', 'null' => false, 'default' => null),
					'article_id' => array('type' => 'integer', 'null' => false, 'default' => null, 'unsigned' => false),
					'user_id' => array('type' => 'integer', 'null' => false, 'default' => null, 'unsigned' => false),
					'msg_id' => array('type' => 'biginteger', 'null' => false, 'default' => null, 'unsigned' => false),
					'parent_id' => array('type' => 'biginteger', 'null' => true, 'default' => null, 'unsigned' => false),
					'indexes' => array(
						'PRIMARY' => array('column' => 'id', 'unique' => 1),
					),
					'tableParameters' => array('charset' => 'utf8', 'collate' => 'utf8_general_ci', 'engine' => 'InnoDB'),
				),
				'articles' => array(
					'id' => array('type' => 'integer', 'null' => false, 'default' => null, 'unsigned' => false, 'key' => 'primary'),
					'owner_id' => array('type' => 'integer', 'null' => false, 'default' => null, 'unsigned' => false),
					'group_id' => array('type' => 'integer', 'null' => true, 'default' => null, 'unsigned' => false),
					'title' => array('type' => 'string', 'null' => true, 'default' => null, 'length' => 1023, 'collate' => 'utf8_general_ci', 'charset' => 'utf8'),
					'body' => array('type' => 'text', 'null' => true, 'default' => null, 'collate' => 'utf8_general_ci', 'charset' => 'utf8'),
					'video_url' => array('type' => 'string', 'null' => true, 'default' => null, 'length' => 1023, 'collate' => 'utf8_general_ci', 'charset' => 'utf8'),
					'type' => array('type' => 'string', 'null' => false, 'default' => 'text', 'length' => 10, 'collate' => 'utf8_general_ci', 'charset' => 'utf8'),
					'published' => array('type' => 'boolean', 'null' => false, 'default' => '0'),
					'created' => array('type' => 'timestamp', 'null' => false, 'default' => null),
					'modified' => array('type' => 'timestamp', 'null' => false, 'default' => '0000-00-00 00:00:00'),
					'cat_id' => array('type' => 'integer', 'null' => false, 'default' => null, 'unsigned' => true, 'key' => 'index'),
					'deleted' => array('type' => 'integer', 'null' => false, 'default' => '0', 'length' => 2, 'unsigned' => false),
					'indexes' => array(
						'PRIMARY' => array('column' => 'id', 'unique' => 1),
						'cat_id' => array('column' => 'cat_id', 'unique' => 0),
					),
					'tableParameters' => array('charset' => 'utf8', 'collate' => 'utf8_general_ci', 'engine' => 'InnoDB'),
				),
				'balance_operations' => array(
					'id' => array('type' => 'integer', 'null' => false, 'default' => null, 'unsigned' => false, 'key' => 'primary'),
					'user_id' => array('type' => 'integer', 'null' => false, 'default' => null, 'unsigned' => false, 'key' => 'index'),
					'oper_type' => array('type' => 'integer', 'null' => true, 'default' => null, 'length' => 1, 'unsigned' => false),
					'sum' => array('type' => 'float', 'null' => false, 'default' => null, 'unsigned' => false),
					'descr' => array('type' => 'text', 'null' => true, 'default' => null, 'collate' => 'utf8_general_ci', 'charset' => 'utf8'),
					'created' => array('type' => 'datetime', 'null' => true, 'default' => null),
					'indexes' => array(
						'PRIMARY' => array('column' => 'id', 'unique' => 1),
						'balance_operations_user_id_idx' => array('column' => 'user_id', 'unique' => 0),
					),
					'tableParameters' => array('charset' => 'utf8', 'collate' => 'utf8_general_ci', 'engine' => 'InnoDB'),
				),
				'chat_contacts' => array(
					'id' => array('type' => 'integer', 'null' => false, 'default' => null, 'unsigned' => true, 'key' => 'primary'),
					'created' => array('type' => 'timestamp', 'null' => false, 'default' => null),
					'modified' => array('type' => 'timestamp', 'null' => true, 'default' => null),
					'user_id' => array('type' => 'integer', 'null' => false, 'default' => null, 'unsigned' => true, 'key' => 'index'),
					'initiator_id' => array('type' => 'integer', 'null' => false, 'default' => null, 'unsigned' => true),
					'active_count' => array('type' => 'integer', 'null' => false, 'default' => '0', 'unsigned' => true),
					'msg' => array('type' => 'text', 'null' => true, 'default' => null, 'collate' => 'utf8_general_ci', 'charset' => 'utf8'),
					'room_id' => array('type' => 'integer', 'null' => false, 'default' => null, 'unsigned' => true),
					'chat_event_id' => array('type' => 'integer', 'null' => false, 'default' => null, 'unsigned' => true),
					'group_id' => array('type' => 'integer', 'null' => true, 'default' => null, 'unsigned' => true),
					'indexes' => array(
						'PRIMARY' => array('column' => 'id', 'unique' => 1),
						'user_id_room_id' => array('column' => array('user_id', 'room_id'), 'unique' => 0),
						'user_id_modified' => array('column' => array('user_id', 'modified'), 'unique' => 0),
					),
					'tableParameters' => array('charset' => 'utf8', 'collate' => 'utf8_general_ci', 'engine' => 'InnoDB'),
				),
				'chat_events' => array(
					'id' => array('type' => 'biginteger', 'null' => false, 'default' => null, 'unsigned' => true, 'key' => 'primary'),
					'user_id' => array('type' => 'integer', 'null' => false, 'default' => null, 'unsigned' => true, 'key' => 'index'),
					'active' => array('type' => 'boolean', 'null' => false, 'default' => '0'),
					'room_id' => array('type' => 'biginteger', 'null' => false, 'default' => null, 'unsigned' => true),
					'created' => array('type' => 'timestamp', 'null' => false, 'default' => null, 'key' => 'index'),
					'event_type' => array('type' => 'integer', 'null' => false, 'default' => '0', 'length' => 4, 'unsigned' => true),
					'initiator_id' => array('type' => 'integer', 'null' => false, 'default' => null, 'unsigned' => true),
					'recipient_id' => array('type' => 'integer', 'null' => true, 'default' => null, 'unsigned' => true),
					'msg_id' => array('type' => 'biginteger', 'null' => true, 'default' => null, 'unsigned' => true),
					'file_id' => array('type' => 'biginteger', 'null' => true, 'default' => null, 'unsigned' => true),
					'indexes' => array(
						'PRIMARY' => array('column' => 'id', 'unique' => 1),
						'user_events' => array('column' => array('user_id', 'active', 'room_id', 'created'), 'unique' => 0),
						'created' => array('column' => 'created', 'unique' => 0),
					),
					'tableParameters' => array('charset' => 'utf8', 'collate' => 'utf8_general_ci', 'engine' => 'InnoDB'),
				),
				'chat_members' => array(
					'id' => array('type' => 'biginteger', 'null' => false, 'default' => null, 'unsigned' => true, 'key' => 'primary'),
					'room_id' => array('type' => 'biginteger', 'null' => false, 'default' => null, 'unsigned' => true, 'key' => 'index'),
					'user_id' => array('type' => 'integer', 'null' => false, 'default' => null, 'unsigned' => true, 'key' => 'index'),
					'is_deleted' => array('type' => 'boolean', 'null' => false, 'default' => '0'),
					'indexes' => array(
						'PRIMARY' => array('column' => 'id', 'unique' => 1),
						'room_id' => array('column' => array('room_id', 'user_id'), 'unique' => 0),
						'user_id' => array('column' => array('user_id', 'room_id'), 'unique' => 0),
					),
					'tableParameters' => array('charset' => 'utf8', 'collate' => 'utf8_general_ci', 'engine' => 'InnoDB'),
				),
				'chat_messages' => array(
					'id' => array('type' => 'biginteger', 'null' => false, 'default' => null, 'unsigned' => true, 'key' => 'primary'),
					'message' => array('type' => 'text', 'null' => true, 'default' => null, 'collate' => 'utf8_general_ci', 'charset' => 'utf8'),
					'indexes' => array(
						'PRIMARY' => array('column' => 'id', 'unique' => 1),
					),
					'tableParameters' => array('charset' => 'utf8', 'collate' => 'utf8_general_ci', 'engine' => 'InnoDB'),
				),
				'chat_rooms' => array(
					'id' => array('type' => 'biginteger', 'null' => false, 'default' => null, 'unsigned' => true, 'key' => 'primary'),
					'created' => array('type' => 'timestamp', 'null' => false, 'default' => null),
					'initiator_id' => array('type' => 'integer', 'null' => false, 'default' => null, 'unsigned' => true, 'key' => 'index'),
					'recipient_id' => array('type' => 'integer', 'null' => false, 'default' => null, 'unsigned' => true),
					'group_id' => array('type' => 'integer', 'null' => true, 'default' => null, 'unsigned' => true),
					'indexes' => array(
						'PRIMARY' => array('column' => 'id', 'unique' => 1),
						'initiator_id' => array('column' => array('initiator_id', 'recipient_id'), 'unique' => 0),
					),
					'tableParameters' => array('charset' => 'utf8', 'collate' => 'utf8_general_ci', 'engine' => 'InnoDB'),
				),
				'cloud' => array(
					'id' => array('type' => 'integer', 'null' => false, 'default' => null, 'unsigned' => true, 'key' => 'primary'),
					'created' => array('type' => 'timestamp', 'null' => true, 'default' => null),
					'modified' => array('type' => 'timestamp', 'null' => true, 'default' => null),
					'user_id' => array('type' => 'integer', 'null' => true, 'default' => null, 'unsigned' => true, 'key' => 'index'),
					'parent_id' => array('type' => 'integer', 'null' => true, 'default' => null, 'unsigned' => true, 'key' => 'index'),
					'name' => array('type' => 'string', 'null' => true, 'collate' => 'utf8_general_ci', 'charset' => 'utf8'),
					'media_id' => array('type' => 'integer', 'null' => false, 'default' => null, 'unsigned' => true),
					'lft' => array('type' => 'integer', 'null' => true, 'default' => null, 'unsigned' => false),
					'rght' => array('type' => 'integer', 'null' => true, 'default' => null, 'unsigned' => false),
					'indexes' => array(
						'PRIMARY' => array('column' => 'id', 'unique' => 1),
						'user_id' => array('column' => 'user_id', 'unique' => 0),
						'parent_id' => array('column' => array('parent_id', 'user_id'), 'unique' => 0),
					),
					'tableParameters' => array('charset' => 'utf8', 'collate' => 'utf8_general_ci', 'engine' => 'InnoDB'),
				),
				'contractors' => array(
					'id' => array('type' => 'integer', 'null' => false, 'default' => null, 'unsigned' => true, 'key' => 'primary'),
					'created' => array('type' => 'timestamp', 'null' => false, 'default' => null),
					'modified' => array('type' => 'timestamp', 'null' => true, 'default' => '0000-00-00 00:00:00'),
					'title' => array('type' => 'string', 'null' => false, 'default' => null, 'length' => 511, 'collate' => 'utf8_general_ci', 'charset' => 'utf8'),
					'contact_person' => array('type' => 'string', 'null' => true, 'default' => null, 'collate' => 'utf8_general_ci', 'charset' => 'utf8'),
					'phone' => array('type' => 'string', 'null' => true, 'default' => null, 'collate' => 'utf8_general_ci', 'charset' => 'utf8'),
					'email' => array('type' => 'string', 'null' => true, 'default' => null, 'collate' => 'utf8_general_ci', 'charset' => 'utf8'),
					'details' => array('type' => 'text', 'null' => true, 'default' => null, 'collate' => 'utf8_general_ci', 'charset' => 'utf8'),
					'indexes' => array(
						'PRIMARY' => array('column' => 'id', 'unique' => 1),
					),
					'tableParameters' => array('charset' => 'utf8', 'collate' => 'utf8_general_ci', 'engine' => 'InnoDB'),
				),
				'countries' => array(
					'id' => array('type' => 'integer', 'null' => false, 'default' => null, 'length' => 5, 'unsigned' => true, 'key' => 'primary'),
					'country_code' => array('type' => 'string', 'null' => false, 'length' => 2, 'collate' => 'utf8_general_ci', 'charset' => 'utf8'),
					'country_name' => array('type' => 'string', 'null' => false, 'length' => 45, 'collate' => 'utf8_general_ci', 'charset' => 'utf8'),
					'show_main' => array('type' => 'integer', 'null' => false, 'default' => '0', 'length' => 4, 'unsigned' => false),
					'indexes' => array(
						'PRIMARY' => array('column' => 'id', 'unique' => 1),
					),
					'tableParameters' => array('charset' => 'utf8', 'collate' => 'utf8_general_ci', 'engine' => 'MyISAM'),
				),
				'crm_tasks' => array(
					'id' => array('type' => 'integer', 'null' => false, 'default' => null, 'unsigned' => true, 'key' => 'primary'),
					'task_id' => array('type' => 'integer', 'null' => false, 'default' => null, 'unsigned' => true),
					'contractor_id' => array('type' => 'integer', 'null' => true, 'default' => null, 'unsigned' => true),
					'money' => array('type' => 'decimal', 'null' => false, 'default' => '0.00', 'length' => '15,2', 'unsigned' => false),
					'currency' => array('type' => 'string', 'null' => false, 'default' => null, 'length' => 4, 'collate' => 'utf8_general_ci', 'charset' => 'utf8'),
					'account_id' => array('type' => 'integer', 'null' => true, 'default' => null, 'unsigned' => false),
					'indexes' => array(
						'PRIMARY' => array('column' => 'id', 'unique' => 1),
					),
					'tableParameters' => array('charset' => 'utf8', 'collate' => 'utf8_general_ci', 'engine' => 'InnoDB'),
				),
				'faqs' => array(
					'id' => array('type' => 'integer', 'null' => false, 'default' => null, 'unsigned' => true, 'key' => 'primary'),
					'question' => array('type' => 'string', 'null' => false, 'default' => null, 'length' => 1023, 'collate' => 'utf8_general_ci', 'charset' => 'utf8'),
					'answer' => array('type' => 'text', 'null' => true, 'default' => null, 'collate' => 'utf8_general_ci', 'charset' => 'utf8'),
					'indexes' => array(
						'PRIMARY' => array('column' => 'id', 'unique' => 1),
					),
					'tableParameters' => array('charset' => 'utf8', 'collate' => 'utf8_general_ci', 'engine' => 'InnoDB'),
				),
				'favourite_lists' => array(
					'id' => array('type' => 'integer', 'null' => false, 'default' => null, 'unsigned' => false, 'key' => 'primary'),
					'title' => array('type' => 'string', 'null' => false, 'default' => null, 'length' => 1023, 'collate' => 'utf8_general_ci', 'charset' => 'utf8'),
					'user_id' => array('type' => 'integer', 'null' => false, 'default' => null, 'unsigned' => false),
					'indexes' => array(
						'PRIMARY' => array('column' => 'id', 'unique' => 1),
					),
					'tableParameters' => array('charset' => 'utf8', 'collate' => 'utf8_general_ci', 'engine' => 'InnoDB'),
				),
				'favourite_users' => array(
					'id' => array('type' => 'integer', 'null' => false, 'default' => null, 'unsigned' => false, 'key' => 'primary'),
					'user_id' => array('type' => 'integer', 'null' => false, 'default' => null, 'unsigned' => false),
					'fav_user_id' => array('type' => 'integer', 'null' => false, 'default' => null, 'unsigned' => false),
					'favourite_list_id' => array('type' => 'integer', 'null' => false, 'default' => '0', 'unsigned' => false),
					'indexes' => array(
						'PRIMARY' => array('column' => 'id', 'unique' => 1),
					),
					'tableParameters' => array('charset' => 'utf8', 'collate' => 'utf8_general_ci', 'engine' => 'InnoDB'),
				),
				'finance_account' => array(
					'id' => array('type' => 'integer', 'null' => false, 'default' => null, 'length' => 10, 'unsigned' => true, 'key' => 'primary'),
					'project_id' => array('type' => 'integer', 'null' => false, 'default' => null, 'unsigned' => true, 'key' => 'primary'),
					'name' => array('type' => 'string', 'null' => false, 'default' => null, 'length' => 50, 'collate' => 'utf8_general_ci', 'charset' => 'utf8'),
					'type' => array('type' => 'string', 'null' => false, 'default' => null, 'length' => 20, 'collate' => 'utf8_general_ci', 'charset' => 'utf8'),
					'currency' => array('type' => 'string', 'null' => false, 'default' => null, 'length' => 4, 'collate' => 'utf8_general_ci', 'charset' => 'utf8'),
					'indexes' => array(
						'PRIMARY' => array('column' => array('id', 'project_id'), 'unique' => 1),
					),
					'tableParameters' => array('charset' => 'utf8', 'collate' => 'utf8_general_ci', 'engine' => 'InnoDB'),
				),
				'finance_budget' => array(
					'id' => array('type' => 'integer', 'null' => false, 'default' => null, 'unsigned' => true, 'key' => 'primary'),
					'project_id' => array('type' => 'integer', 'null' => false, 'default' => null, 'unsigned' => true),
					'category_id' => array('type' => 'integer', 'null' => false, 'default' => null, 'unsigned' => true),
					'account_id' => array('type' => 'integer', 'null' => false, 'default' => null, 'unsigned' => true),
					'plan' => array('type' => 'decimal', 'null' => false, 'default' => null, 'length' => '15,2', 'unsigned' => false),
					'is_repeat' => array('type' => 'boolean', 'null' => false, 'default' => null),
					'indexes' => array(
						'PRIMARY' => array('column' => 'id', 'unique' => 1),
					),
					'tableParameters' => array('charset' => 'utf8', 'collate' => 'utf8_general_ci', 'engine' => 'InnoDB'),
				),
				'finance_calendar' => array(
					'id' => array('type' => 'integer', 'null' => false, 'default' => null, 'unsigned' => false, 'key' => 'primary'),
					'date' => array('type' => 'date', 'null' => false, 'default' => null),
					'indexes' => array(
						'PRIMARY' => array('column' => 'id', 'unique' => 1),
					),
					'tableParameters' => array('charset' => 'utf8', 'collate' => 'utf8_general_ci', 'engine' => 'InnoDB'),
				),
				'finance_category' => array(
					'id' => array('type' => 'integer', 'null' => false, 'default' => null, 'length' => 10, 'unsigned' => true, 'key' => 'primary'),
					'project_id' => array('type' => 'integer', 'null' => false, 'default' => null, 'unsigned' => true, 'key' => 'primary'),
					'name' => array('type' => 'string', 'null' => false, 'default' => null, 'length' => 100, 'collate' => 'utf8_general_ci', 'charset' => 'utf8'),
					'type' => array('type' => 'integer', 'null' => false, 'default' => null, 'length' => 4, 'unsigned' => false),
					'indexes' => array(
						'PRIMARY' => array('column' => array('id', 'project_id'), 'unique' => 1),
					),
					'tableParameters' => array('charset' => 'utf8', 'collate' => 'utf8_general_ci', 'engine' => 'InnoDB'),
				),
				'finance_goals' => array(
					'id' => array('type' => 'integer', 'null' => false, 'default' => null, 'unsigned' => true, 'key' => 'primary'),
					'project_id' => array('type' => 'integer', 'null' => false, 'default' => null, 'unsigned' => true),
					'account_id' => array('type' => 'integer', 'null' => false, 'default' => null, 'unsigned' => true),
					'name' => array('type' => 'string', 'null' => false, 'default' => null, 'length' => 100, 'collate' => 'utf8_general_ci', 'charset' => 'utf8'),
					'created' => array('type' => 'timestamp', 'null' => false, 'default' => null),
					'finish' => array('type' => 'timestamp', 'null' => false, 'default' => '0000-00-00 00:00:00'),
					'final_sum' => array('type' => 'decimal', 'null' => false, 'default' => null, 'length' => '15,2', 'unsigned' => false),
					'indexes' => array(
						'PRIMARY' => array('column' => 'id', 'unique' => 1),
					),
					'tableParameters' => array('charset' => 'utf8', 'collate' => 'utf8_general_ci', 'engine' => 'InnoDB'),
				),
				'finance_operation' => array(
					'id' => array('type' => 'integer', 'null' => false, 'default' => null, 'length' => 10, 'unsigned' => true, 'key' => 'primary'),
					'project_id' => array('type' => 'integer', 'null' => false, 'default' => null, 'unsigned' => true, 'key' => 'primary'),
					'account_id' => array('type' => 'integer', 'null' => false, 'default' => null, 'unsigned' => true, 'key' => 'primary'),
					'link_id' => array('type' => 'integer', 'null' => true, 'default' => null, 'unsigned' => true),
					'created' => array('type' => 'timestamp', 'null' => true, 'default' => null),
					'type' => array('type' => 'integer', 'null' => false, 'default' => null, 'length' => 4, 'unsigned' => false),
					'amount' => array('type' => 'decimal', 'null' => false, 'default' => null, 'length' => '15,2', 'unsigned' => false),
					'balance_after' => array('type' => 'decimal', 'null' => false, 'default' => null, 'length' => '15,2', 'unsigned' => false),
					'currency' => array('type' => 'string', 'null' => false, 'default' => null, 'length' => 4, 'collate' => 'utf8_general_ci', 'charset' => 'utf8'),
					'is_planned' => array('type' => 'boolean', 'null' => false, 'default' => '0'),
					'comment' => array('type' => 'string', 'null' => false, 'default' => null, 'collate' => 'utf8_general_ci', 'charset' => 'utf8'),
					'indexes' => array(
						'PRIMARY' => array('column' => array('id', 'project_id', 'account_id'), 'unique' => 1),
					),
					'tableParameters' => array('charset' => 'utf8', 'collate' => 'utf8_general_ci', 'engine' => 'InnoDB'),
				),
				'finance_operation_has_category' => array(
					'id' => array('type' => 'integer', 'null' => false, 'default' => null, 'unsigned' => true, 'key' => 'primary'),
					'operation_id' => array('type' => 'integer', 'null' => false, 'default' => null, 'unsigned' => true, 'key' => 'primary'),
					'category_id' => array('type' => 'integer', 'null' => false, 'default' => null, 'unsigned' => true, 'key' => 'primary'),
					'indexes' => array(
						'PRIMARY' => array('column' => array('id', 'operation_id', 'category_id'), 'unique' => 1),
					),
					'tableParameters' => array('charset' => 'utf8', 'collate' => 'utf8_general_ci', 'engine' => 'InnoDB'),
				),
				'finance_project' => array(
					'id' => array('type' => 'integer', 'null' => false, 'default' => null, 'unsigned' => true, 'key' => 'primary'),
					'user_id' => array('type' => 'integer', 'null' => false, 'default' => null, 'unsigned' => false),
					'name' => array('type' => 'string', 'null' => false, 'default' => null, 'length' => 100, 'collate' => 'utf8_general_ci', 'charset' => 'utf8'),
					'hidden' => array('type' => 'boolean', 'null' => false, 'default' => null),
					'indexes' => array(
						'PRIMARY' => array('column' => 'id', 'unique' => 1),
					),
					'tableParameters' => array('charset' => 'utf8', 'collate' => 'utf8_general_ci', 'engine' => 'InnoDB'),
				),
				'finance_share' => array(
					'id' => array('type' => 'integer', 'null' => false, 'default' => null, 'unsigned' => true, 'key' => 'primary'),
					'project_id' => array('type' => 'integer', 'null' => false, 'default' => null, 'unsigned' => true),
					'user_id' => array('type' => 'integer', 'null' => false, 'default' => null, 'unsigned' => true),
					'state' => array('type' => 'integer', 'null' => false, 'default' => null, 'length' => 2, 'unsigned' => true),
					'full_access' => array('type' => 'boolean', 'null' => false, 'default' => '0'),
					'accounts' => array('type' => 'string', 'null' => false, 'length' => 2048, 'collate' => 'utf8_general_ci', 'charset' => 'utf8'),
					'operations' => array('type' => 'string', 'null' => false, 'length' => 2048, 'collate' => 'utf8_general_ci', 'charset' => 'utf8'),
					'categories' => array('type' => 'string', 'null' => false, 'length' => 2048, 'collate' => 'utf8_general_ci', 'charset' => 'utf8'),
					'budgets' => array('type' => 'string', 'null' => false, 'length' => 2048, 'collate' => 'utf8_general_ci', 'charset' => 'utf8'),
					'goals' => array('type' => 'string', 'null' => false, 'length' => 2048, 'collate' => 'utf8_general_ci', 'charset' => 'utf8'),
					'indexes' => array(
						'PRIMARY' => array('column' => 'id', 'unique' => 1),
					),
					'tableParameters' => array('charset' => 'utf8', 'collate' => 'utf8_general_ci', 'engine' => 'InnoDB'),
				),
				'group_achievements' => array(
					'id' => array('type' => 'integer', 'null' => false, 'default' => null, 'unsigned' => true, 'key' => 'primary'),
					'created' => array('type' => 'timestamp', 'null' => false, 'default' => null),
					'group_id' => array('type' => 'integer', 'null' => false, 'default' => null, 'unsigned' => true, 'key' => 'index'),
					'title' => array('type' => 'text', 'null' => true, 'default' => null, 'collate' => 'utf8_general_ci', 'charset' => 'utf8'),
					'url' => array('type' => 'string', 'null' => true, 'default' => null, 'length' => 1023, 'collate' => 'utf8_general_ci', 'charset' => 'utf8'),
					'indexes' => array(
						'PRIMARY' => array('column' => 'id', 'unique' => 1),
						'group_id' => array('column' => 'group_id', 'unique' => 0),
					),
					'tableParameters' => array('charset' => 'utf8', 'collate' => 'utf8_general_ci', 'engine' => 'InnoDB'),
				),
				'group_addresses' => array(
					'id' => array('type' => 'integer', 'null' => false, 'default' => null, 'unsigned' => true, 'key' => 'primary'),
					'group_id' => array('type' => 'integer', 'null' => false, 'default' => null, 'unsigned' => true, 'key' => 'index'),
					'address' => array('type' => 'text', 'null' => true, 'default' => null, 'collate' => 'utf8_general_ci', 'charset' => 'utf8'),
					'phone' => array('type' => 'string', 'null' => true, 'default' => null, 'length' => 1023, 'collate' => 'utf8_general_ci', 'charset' => 'utf8'),
					'email' => array('type' => 'string', 'null' => true, 'default' => null, 'length' => 1023, 'collate' => 'utf8_general_ci', 'charset' => 'utf8'),
					'url' => array('type' => 'string', 'null' => true, 'default' => null, 'length' => 1023, 'collate' => 'utf8_general_ci', 'charset' => 'utf8'),
					'fax' => array('type' => 'string', 'null' => true, 'default' => null, 'length' => 1023, 'collate' => 'utf8_general_ci', 'charset' => 'utf8'),
					'country' => array('type' => 'string', 'null' => true, 'default' => null, 'length' => 1023, 'collate' => 'utf8_general_ci', 'charset' => 'utf8'),
					'zip_code' => array('type' => 'string', 'null' => true, 'default' => null, 'collate' => 'utf8_general_ci', 'charset' => 'utf8'),
					'head_office' => array('type' => 'boolean', 'null' => false, 'default' => '0'),
					'indexes' => array(
						'PRIMARY' => array('column' => 'id', 'unique' => 1),
						'group_id' => array('column' => 'group_id', 'unique' => 0),
					),
					'tableParameters' => array('charset' => 'utf8', 'collate' => 'utf8_general_ci', 'engine' => 'InnoDB'),
				),
				'group_categories' => array(
					'id' => array('type' => 'integer', 'null' => false, 'default' => null, 'unsigned' => false, 'key' => 'primary'),
					'name' => array('type' => 'string', 'null' => false, 'default' => null, 'length' => 63, 'collate' => 'utf8_general_ci', 'charset' => 'utf8'),
					'indexes' => array(
						'PRIMARY' => array('column' => 'id', 'unique' => 1),
					),
					'tableParameters' => array('charset' => 'utf8', 'collate' => 'utf8_general_ci', 'engine' => 'InnoDB'),
				),
				'group_members' => array(
					'id' => array('type' => 'integer', 'null' => false, 'default' => null, 'unsigned' => true, 'key' => 'primary'),
					'created' => array('type' => 'timestamp', 'null' => false, 'default' => null),
					'group_id' => array('type' => 'integer', 'null' => false, 'default' => null, 'unsigned' => true, 'key' => 'index'),
					'user_id' => array('type' => 'integer', 'null' => false, 'default' => null, 'unsigned' => true, 'key' => 'index'),
					'role' => array('type' => 'string', 'null' => true, 'default' => null, 'length' => 1023, 'collate' => 'utf8_general_ci', 'charset' => 'utf8'),
					'approved' => array('type' => 'boolean', 'null' => false, 'default' => '0'),
					'approve_date' => array('type' => 'timestamp', 'null' => false, 'default' => '0000-00-00 00:00:00'),
					'wages' => array('type' => 'integer', 'null' => false, 'default' => '0', 'length' => 4, 'unsigned' => false),
					'sort_order' => array('type' => 'integer', 'null' => false, 'default' => '1', 'unsigned' => true),
					'show_main' => array('type' => 'boolean', 'null' => false, 'default' => '0'),
					'is_invited' => array('type' => 'boolean', 'null' => false, 'default' => '0'),
					'is_deleted' => array('type' => 'boolean', 'null' => false, 'default' => '0'),
					'indexes' => array(
						'PRIMARY' => array('column' => 'id', 'unique' => 1),
						'group_user' => array('column' => array('group_id', 'user_id'), 'unique' => 0),
						'user_group' => array('column' => array('user_id', 'group_id'), 'unique' => 0),
						'group_created' => array('column' => array('group_id', 'created'), 'unique' => 0),
						'group_sort_order' => array('column' => array('group_id', 'sort_order'), 'unique' => 0),
					),
					'tableParameters' => array('charset' => 'utf8', 'collate' => 'utf8_general_ci', 'engine' => 'InnoDB'),
				),
				'group_vacancy' => array(
					'id' => array('type' => 'integer', 'null' => false, 'default' => null, 'unsigned' => false, 'key' => 'primary'),
					'group_id' => array('type' => 'integer', 'null' => false, 'default' => null, 'unsigned' => false),
					'title' => array('type' => 'string', 'null' => false, 'default' => null, 'collate' => 'latin1_swedish_ci', 'charset' => 'latin1'),
					'descr' => array('type' => 'string', 'null' => false, 'default' => null, 'length' => 2047, 'collate' => 'latin1_swedish_ci', 'charset' => 'latin1'),
					'country' => array('type' => 'string', 'null' => false, 'default' => null, 'length' => 15, 'collate' => 'latin1_swedish_ci', 'charset' => 'latin1'),
					'city' => array('type' => 'string', 'null' => false, 'default' => null, 'length' => 1023, 'collate' => 'latin1_swedish_ci', 'charset' => 'latin1'),
					'wage' => array('type' => 'integer', 'null' => false, 'default' => '0', 'length' => 10, 'unsigned' => true),
					'currency' => array('type' => 'string', 'null' => false, 'default' => 'USD', 'length' => 12, 'collate' => 'latin1_swedish_ci', 'charset' => 'latin1'),
					'employment' => array('type' => 'integer', 'null' => false, 'default' => '0', 'length' => 3, 'unsigned' => true),
					'shedule' => array('type' => 'integer', 'null' => false, 'default' => '0', 'length' => 3, 'unsigned' => true),
					'experience' => array('type' => 'float', 'null' => false, 'default' => '0', 'unsigned' => false),
					'open' => array('type' => 'boolean', 'null' => false, 'default' => '0'),
					'created' => array('type' => 'timestamp', 'null' => false, 'default' => null),
					'indexes' => array(
						'PRIMARY' => array('column' => 'id', 'unique' => 1),
					),
					'tableParameters' => array('charset' => 'latin1', 'collate' => 'latin1_swedish_ci', 'engine' => 'InnoDB'),
				),
				'group_videos' => array(
					'id' => array('type' => 'integer', 'null' => false, 'default' => null, 'unsigned' => true, 'key' => 'primary'),
					'created' => array('type' => 'timestamp', 'null' => false, 'default' => null),
					'group_id' => array('type' => 'integer', 'null' => false, 'default' => null, 'unsigned' => true, 'key' => 'index'),
					'url' => array('type' => 'string', 'null' => true, 'default' => null, 'length' => 1023, 'collate' => 'utf8_general_ci', 'charset' => 'utf8'),
					'video_id' => array('type' => 'string', 'null' => false, 'default' => null, 'length' => 1023, 'collate' => 'utf8_general_ci', 'charset' => 'utf8'),
					'indexes' => array(
						'PRIMARY' => array('column' => 'id', 'unique' => 1),
						'group_id' => array('column' => 'group_id', 'unique' => 0),
					),
					'tableParameters' => array('charset' => 'utf8', 'collate' => 'utf8_general_ci', 'engine' => 'InnoDB'),
				),
				'groups' => array(
					'id' => array('type' => 'integer', 'null' => false, 'default' => null, 'unsigned' => true, 'key' => 'primary'),
					'created' => array('type' => 'timestamp', 'null' => false, 'default' => null),
					'owner_id' => array('type' => 'integer', 'null' => false, 'default' => null, 'unsigned' => true, 'key' => 'index'),
					'responsible_id' => array('type' => 'integer', 'null' => true, 'default' => null, 'unsigned' => false),
					'title' => array('type' => 'string', 'null' => false, 'default' => null, 'length' => 1023, 'key' => 'index', 'collate' => 'utf8_general_ci', 'charset' => 'utf8'),
					'descr' => array('type' => 'text', 'null' => true, 'default' => null, 'collate' => 'utf8_general_ci', 'charset' => 'utf8'),
					'finance_project_id' => array('type' => 'integer', 'null' => true, 'default' => null, 'unsigned' => false),
					'hidden' => array('type' => 'boolean', 'null' => false, 'default' => '0'),
					'group_url' => array('type' => 'string', 'null' => true, 'default' => null, 'length' => 32, 'collate' => 'utf8_general_ci', 'charset' => 'utf8'),
					'video_url' => array('type' => 'string', 'null' => true, 'default' => null, 'length' => 1023, 'collate' => 'utf8_general_ci', 'charset' => 'utf8'),
					'cat_id' => array('type' => 'integer', 'null' => false, 'default' => '0', 'unsigned' => false),
					'indexes' => array(
						'PRIMARY' => array('column' => 'id', 'unique' => 1),
						'owner_created' => array('column' => array('owner_id', 'created'), 'unique' => 0),
						'title' => array('column' => 'title', 'unique' => 0, 'length' => array('255')),
					),
					'tableParameters' => array('charset' => 'utf8', 'collate' => 'utf8_general_ci', 'engine' => 'InnoDB'),
				),
				'invest_category' => array(
					'id' => array('type' => 'integer', 'null' => false, 'default' => null, 'unsigned' => true, 'key' => 'primary'),
					'title' => array('type' => 'string', 'null' => false, 'default' => null, 'length' => 100, 'collate' => 'utf8_general_ci', 'charset' => 'utf8'),
					'sort_order' => array('type' => 'integer', 'null' => false, 'default' => '0', 'unsigned' => true),
					'indexes' => array(
						'PRIMARY' => array('column' => 'id', 'unique' => 1),
					),
					'tableParameters' => array('charset' => 'utf8', 'collate' => 'utf8_general_ci', 'engine' => 'InnoDB'),
				),
				'invest_project' => array(
					'id' => array('type' => 'integer', 'null' => false, 'default' => null, 'unsigned' => true, 'key' => 'primary'),
					'category_id' => array('type' => 'integer', 'null' => false, 'default' => null, 'unsigned' => true),
					'user_id' => array('type' => 'integer', 'null' => false, 'default' => null, 'unsigned' => true),
					'name' => array('type' => 'string', 'null' => false, 'default' => null, 'collate' => 'utf8_general_ci', 'charset' => 'utf8'),
					'note' => array('type' => 'text', 'null' => false, 'default' => null, 'collate' => 'utf8_general_ci', 'charset' => 'utf8'),
					'total' => array('type' => 'decimal', 'null' => true, 'default' => null, 'length' => '15,2', 'unsigned' => false),
					'duration' => array('type' => 'integer', 'null' => false, 'default' => null, 'length' => 4, 'unsigned' => false),
					'body' => array('type' => 'text', 'null' => false, 'default' => null, 'collate' => 'utf8_general_ci', 'charset' => 'utf8'),
					'video' => array('type' => 'string', 'null' => false, 'default' => null, 'length' => 1023, 'collate' => 'utf8_general_ci', 'charset' => 'utf8'),
					'created' => array('type' => 'timestamp', 'null' => false, 'default' => null),
					'currency' => array('type' => 'string', 'null' => false, 'default' => null, 'length' => 6, 'collate' => 'utf8_general_ci', 'charset' => 'utf8'),
					'indexes' => array(
						'PRIMARY' => array('column' => 'id', 'unique' => 1),
					),
					'tableParameters' => array('charset' => 'utf8', 'collate' => 'utf8_general_ci', 'engine' => 'InnoDB'),
				),
				'invest_reward' => array(
					'id' => array('type' => 'integer', 'null' => false, 'default' => null, 'unsigned' => true, 'key' => 'primary'),
					'user_id' => array('type' => 'integer', 'null' => false, 'default' => null, 'unsigned' => true),
					'project_id' => array('type' => 'integer', 'null' => false, 'default' => null, 'unsigned' => true),
					'name' => array('type' => 'string', 'null' => false, 'default' => null, 'collate' => 'utf8_general_ci', 'charset' => 'utf8'),
					'description' => array('type' => 'text', 'null' => false, 'default' => null, 'collate' => 'utf8_general_ci', 'charset' => 'utf8'),
					'total' => array('type' => 'decimal', 'null' => true, 'default' => null, 'length' => '15,2', 'unsigned' => false),
					'created' => array('type' => 'timestamp', 'null' => false, 'default' => null),
					'indexes' => array(
						'PRIMARY' => array('column' => 'id', 'unique' => 1),
					),
					'tableParameters' => array('charset' => 'utf8', 'collate' => 'utf8_general_ci', 'engine' => 'InnoDB'),
				),
				'invest_sponsor' => array(
					'id' => array('type' => 'integer', 'null' => false, 'default' => null, 'unsigned' => true, 'key' => 'primary'),
					'user_id' => array('type' => 'integer', 'null' => false, 'default' => null, 'unsigned' => true),
					'reward_id' => array('type' => 'integer', 'null' => false, 'default' => null, 'unsigned' => true),
					'amount' => array('type' => 'decimal', 'null' => false, 'default' => null, 'length' => '15,2', 'unsigned' => false),
					'currency' => array('type' => 'string', 'null' => false, 'default' => null, 'length' => 4, 'collate' => 'utf8_general_ci', 'charset' => 'utf8'),
					'created' => array('type' => 'timestamp', 'null' => false, 'default' => null),
					'indexes' => array(
						'PRIMARY' => array('column' => 'id', 'unique' => 1),
					),
					'tableParameters' => array('charset' => 'utf8', 'collate' => 'utf8_general_ci', 'engine' => 'InnoDB'),
				),
				'invest_video' => array(
					'id' => array('type' => 'integer', 'null' => false, 'default' => null, 'unsigned' => true, 'key' => 'primary'),
					'project_id' => array('type' => 'integer', 'null' => false, 'default' => null, 'unsigned' => true),
					'youtube_id' => array('type' => 'string', 'null' => false, 'default' => null, 'length' => 50, 'collate' => 'utf8_general_ci', 'charset' => 'utf8'),
					'indexes' => array(
						'PRIMARY' => array('column' => 'id', 'unique' => 1),
					),
					'tableParameters' => array('charset' => 'utf8', 'collate' => 'utf8_general_ci', 'engine' => 'InnoDB'),
				),
				'media' => array(
					'id' => array('type' => 'integer', 'null' => false, 'default' => null, 'unsigned' => true, 'key' => 'primary'),
					'created' => array('type' => 'timestamp', 'null' => false, 'default' => null),
					'media_type' => array('type' => 'string', 'null' => false, 'default' => 'bin_file', 'length' => 10, 'key' => 'index', 'collate' => 'utf8_general_ci', 'charset' => 'utf8'),
					'object_type' => array('type' => 'string', 'null' => false, 'default' => 'Article', 'length' => 50, 'key' => 'index', 'collate' => 'utf8_general_ci', 'charset' => 'utf8'),
					'object_id' => array('type' => 'integer', 'null' => true, 'default' => null, 'unsigned' => true),
					'file' => array('type' => 'string', 'null' => true, 'default' => null, 'collate' => 'utf8_general_ci', 'charset' => 'utf8'),
					'ext' => array('type' => 'string', 'null' => true, 'default' => null, 'length' => 10, 'collate' => 'utf8_general_ci', 'charset' => 'utf8'),
					'main' => array('type' => 'boolean', 'null' => false, 'default' => '0'),
					'orig_fname' => array('type' => 'string', 'null' => true, 'default' => null, 'collate' => 'utf8_general_ci', 'charset' => 'utf8'),
					'orig_fsize' => array('type' => 'biginteger', 'null' => true, 'default' => null, 'unsigned' => true),
					'orig_w' => array('type' => 'integer', 'null' => true, 'default' => null, 'unsigned' => true),
					'orig_h' => array('type' => 'integer', 'null' => true, 'default' => null, 'unsigned' => true),
					'indexes' => array(
						'PRIMARY' => array('column' => 'id', 'unique' => 1),
						'media_type' => array('column' => array('media_type', 'object_type', 'object_id', 'main'), 'unique' => 0),
						'object_type_id' => array('column' => array('object_type', 'object_id'), 'unique' => 0),
					),
					'tableParameters' => array('charset' => 'utf8', 'collate' => 'utf8_general_ci', 'engine' => 'InnoDB'),
				),
				'notes' => array(
					'id' => array('type' => 'integer', 'null' => false, 'default' => null, 'unsigned' => false, 'key' => 'primary'),
					'user_id' => array('type' => 'integer', 'null' => false, 'default' => null, 'unsigned' => false),
					'title' => array('type' => 'string', 'null' => false, 'default' => null, 'length' => 1023, 'collate' => 'utf8_general_ci', 'charset' => 'utf8'),
					'body' => array('type' => 'text', 'null' => true, 'default' => null, 'collate' => 'utf8_general_ci', 'charset' => 'utf8'),
					'type' => array('type' => 'string', 'null' => false, 'default' => 'text', 'length' => 8, 'collate' => 'utf8_general_ci', 'charset' => 'utf8'),
					'table_id' => array('type' => 'string', 'null' => true, 'default' => null, 'length' => 32, 'collate' => 'utf8_general_ci', 'charset' => 'utf8'),
					'is_folder' => array('type' => 'integer', 'null' => false, 'default' => '0', 'length' => 2, 'unsigned' => false),
					'parent_id' => array('type' => 'integer', 'null' => true, 'default' => null, 'unsigned' => false),
					'lft' => array('type' => 'integer', 'null' => false, 'default' => null, 'unsigned' => false),
					'rght' => array('type' => 'integer', 'null' => false, 'default' => null, 'unsigned' => false),
					'created' => array('type' => 'timestamp', 'null' => false, 'default' => null),
					'modified' => array('type' => 'timestamp', 'null' => false, 'default' => '0000-00-00 00:00:00'),
					'indexes' => array(
						'PRIMARY' => array('column' => 'id', 'unique' => 1),
					),
					'tableParameters' => array('charset' => 'utf8', 'collate' => 'utf8_general_ci', 'engine' => 'InnoDB'),
				),
				'order_products' => array(
					'id' => array('type' => 'integer', 'null' => false, 'default' => null, 'unsigned' => true, 'key' => 'primary'),
					'created' => array('type' => 'timestamp', 'null' => false, 'default' => null),
					'modified' => array('type' => 'timestamp', 'null' => true, 'default' => '0000-00-00 00:00:00'),
					'order_id' => array('type' => 'integer', 'null' => false, 'default' => null, 'unsigned' => true, 'key' => 'index'),
					'product_id' => array('type' => 'integer', 'null' => false, 'default' => null, 'unsigned' => true, 'key' => 'index'),
					'user_id' => array('type' => 'integer', 'null' => false, 'default' => '0', 'unsigned' => true),
					'blocked' => array('type' => 'boolean', 'null' => false, 'default' => '0'),
					'distrib_date' => array('type' => 'timestamp', 'null' => true, 'default' => '0000-00-00 00:00:00'),
					'indexes' => array(
						'PRIMARY' => array('column' => 'id', 'unique' => 1),
						'order_id' => array('column' => array('order_id', 'product_id'), 'unique' => 0),
						'product_id' => array('column' => array('product_id', 'order_id'), 'unique' => 0),
					),
					'tableParameters' => array('charset' => 'utf8', 'collate' => 'utf8_general_ci', 'engine' => 'InnoDB'),
				),
				'order_reports' => array(
					'id' => array('type' => 'integer', 'null' => false, 'default' => null, 'unsigned' => true, 'key' => 'primary'),
					'created' => array('type' => 'timestamp', 'null' => true, 'default' => null),
					'modified' => array('type' => 'timestamp', 'null' => true, 'default' => '0000-00-00 00:00:00'),
					'contractor_id' => array('type' => 'integer', 'null' => false, 'default' => null, 'unsigned' => true, 'key' => 'index'),
					'order_id' => array('type' => 'integer', 'null' => false, 'default' => null, 'unsigned' => true),
					'period_count' => array('type' => 'integer', 'null' => false, 'default' => null, 'unsigned' => true),
					'product_type_id' => array('type' => 'integer', 'null' => false, 'default' => null, 'unsigned' => true),
					'product_id' => array('type' => 'integer', 'null' => false, 'default' => null, 'unsigned' => true),
					'qty' => array('type' => 'integer', 'null' => false, 'default' => null, 'unsigned' => true),
					'price' => array('type' => 'float', 'null' => false, 'default' => null, 'length' => '9,2', 'unsigned' => true),
					'oper_id' => array('type' => 'integer', 'null' => true, 'default' => null, 'unsigned' => true),
					'indexes' => array(
						'PRIMARY' => array('column' => 'id', 'unique' => 1),
						'contractor_id' => array('column' => array('contractor_id', 'order_id', 'product_type_id'), 'unique' => 0),
					),
					'tableParameters' => array('charset' => 'utf8', 'collate' => 'utf8_general_ci', 'engine' => 'InnoDB'),
				),
				'order_types' => array(
					'id' => array('type' => 'integer', 'null' => false, 'default' => null, 'unsigned' => true, 'key' => 'primary'),
					'order_id' => array('type' => 'integer', 'null' => false, 'default' => null, 'unsigned' => true, 'key' => 'index'),
					'product_type_id' => array('type' => 'integer', 'null' => false, 'default' => null, 'unsigned' => true),
					'qty' => array('type' => 'integer', 'null' => false, 'default' => '0', 'unsigned' => true),
					'indexes' => array(
						'PRIMARY' => array('column' => 'id', 'unique' => 1),
						'order_id_product_type_id' => array('column' => array('order_id', 'product_type_id'), 'unique' => 0),
					),
					'tableParameters' => array('charset' => 'utf8', 'collate' => 'utf8_general_ci', 'engine' => 'InnoDB'),
				),
				'orders' => array(
					'id' => array('type' => 'integer', 'null' => false, 'default' => null, 'unsigned' => true, 'key' => 'primary'),
					'created' => array('type' => 'timestamp', 'null' => false, 'default' => null, 'key' => 'index'),
					'modified' => array('type' => 'timestamp', 'null' => false, 'default' => '0000-00-00 00:00:00'),
					'contractor_id' => array('type' => 'integer', 'null' => false, 'default' => null, 'unsigned' => true, 'key' => 'index'),
					'period' => array('type' => 'integer', 'null' => false, 'default' => null, 'unsigned' => true),
					'paid' => array('type' => 'boolean', 'null' => false, 'default' => '0'),
					'shipped' => array('type' => 'boolean', 'null' => false, 'default' => '0'),
					'indexes' => array(
						'PRIMARY' => array('column' => 'id', 'unique' => 1),
						'contractor_id' => array('column' => 'contractor_id', 'unique' => 0),
						'created' => array('column' => 'created', 'unique' => 0),
					),
					'tableParameters' => array('charset' => 'utf8', 'collate' => 'utf8_general_ci', 'engine' => 'InnoDB'),
				),
				'product_types' => array(
					'id' => array('type' => 'integer', 'null' => false, 'default' => null, 'unsigned' => true, 'key' => 'primary'),
					'title' => array('type' => 'string', 'null' => false, 'default' => null, 'collate' => 'utf8_general_ci', 'charset' => 'utf8'),
					'arenda_price' => array('type' => 'float', 'null' => false, 'default' => null, 'length' => '9,2', 'unsigned' => true),
					'teaser' => array('type' => 'string', 'null' => true, 'default' => null, 'length' => 1023, 'collate' => 'utf8_general_ci', 'charset' => 'utf8'),
					'descr' => array('type' => 'text', 'null' => false, 'default' => null, 'collate' => 'utf8_general_ci', 'charset' => 'utf8'),
					'min_qty' => array('type' => 'integer', 'null' => false, 'default' => '0', 'unsigned' => true),
					'indexes' => array(
						'PRIMARY' => array('column' => 'id', 'unique' => 1),
					),
					'tableParameters' => array('charset' => 'utf8', 'collate' => 'utf8_general_ci', 'engine' => 'InnoDB'),
				),
				'products' => array(
					'id' => array('type' => 'integer', 'null' => false, 'default' => null, 'unsigned' => true, 'key' => 'primary'),
					'product_type_id' => array('type' => 'integer', 'null' => false, 'default' => null, 'unsigned' => true, 'key' => 'index'),
					'serial' => array('type' => 'string', 'null' => false, 'default' => null, 'key' => 'index', 'collate' => 'utf8_general_ci', 'charset' => 'utf8'),
					'prev_counter' => array('type' => 'biginteger', 'null' => true, 'default' => '0', 'unsigned' => true),
					'ip' => array('type' => 'string', 'null' => true, 'default' => null, 'collate' => 'utf8_general_ci', 'charset' => 'utf8'),
					'indexes' => array(
						'PRIMARY' => array('column' => 'id', 'unique' => 1),
						'product_type_id' => array('column' => 'product_type_id', 'unique' => 0),
						'serial' => array('column' => 'serial', 'unique' => 0),
					),
					'tableParameters' => array('charset' => 'utf8', 'collate' => 'utf8_general_ci', 'engine' => 'InnoDB'),
				),
				'project_events' => array(
					'id' => array('type' => 'biginteger', 'null' => false, 'default' => null, 'unsigned' => true, 'key' => 'primary'),
					'created' => array('type' => 'timestamp', 'null' => false, 'default' => null, 'key' => 'index'),
					'project_id' => array('type' => 'integer', 'null' => false, 'default' => null, 'unsigned' => true, 'key' => 'index'),
					'user_id' => array('type' => 'integer', 'null' => false, 'default' => null, 'unsigned' => true, 'key' => 'index'),
					'event_type' => array('type' => 'integer', 'null' => false, 'default' => '0', 'length' => 4, 'unsigned' => true),
					'msg_id' => array('type' => 'biginteger', 'null' => true, 'default' => null, 'unsigned' => true),
					'file_id' => array('type' => 'string', 'null' => true, 'default' => null, 'length' => 2048, 'collate' => 'utf8_general_ci', 'charset' => 'utf8'),
					'task_id' => array('type' => 'integer', 'null' => true, 'default' => null, 'unsigned' => true),
					'subproject_id' => array('type' => 'integer', 'null' => true, 'default' => null, 'unsigned' => true),
					'indexes' => array(
						'PRIMARY' => array('column' => 'id', 'unique' => 1),
						'user_id' => array('column' => 'user_id', 'unique' => 0),
						'project_id' => array('column' => 'project_id', 'unique' => 0),
						'created' => array('column' => 'created', 'unique' => 0),
					),
					'tableParameters' => array('charset' => 'utf8', 'collate' => 'utf8_general_ci', 'engine' => 'InnoDB'),
				),
				'project_finances' => array(
					'id' => array('type' => 'integer', 'null' => false, 'default' => null, 'unsigned' => false, 'key' => 'primary'),
					'project_id' => array('type' => 'integer', 'null' => false, 'default' => null, 'unsigned' => false),
					'income_id' => array('type' => 'integer', 'null' => false, 'default' => null, 'unsigned' => false),
					'expense_id' => array('type' => 'integer', 'null' => false, 'default' => null, 'unsigned' => false),
					'tax_id' => array('type' => 'integer', 'null' => false, 'default' => null, 'unsigned' => false),
					'percent_id' => array('type' => 'integer', 'null' => false, 'default' => null, 'unsigned' => false),
					'indexes' => array(
						'PRIMARY' => array('column' => 'id', 'unique' => 1),
					),
					'tableParameters' => array('charset' => 'utf8', 'collate' => 'utf8_general_ci', 'engine' => 'InnoDB'),
				),
				'project_members' => array(
					'id' => array('type' => 'integer', 'null' => false, 'default' => null, 'unsigned' => true, 'key' => 'primary'),
					'created' => array('type' => 'timestamp', 'null' => false, 'default' => null),
					'project_id' => array('type' => 'integer', 'null' => false, 'default' => null, 'unsigned' => true, 'key' => 'index'),
					'user_id' => array('type' => 'integer', 'null' => false, 'default' => null, 'unsigned' => true, 'key' => 'index'),
					'is_responsible' => array('type' => 'boolean', 'null' => false, 'default' => '0'),
					'sort_order' => array('type' => 'integer', 'null' => false, 'default' => '1', 'unsigned' => true),
					'indexes' => array(
						'PRIMARY' => array('column' => 'id', 'unique' => 1),
						'project_user' => array('column' => array('project_id', 'user_id'), 'unique' => 0),
						'user_project' => array('column' => array('user_id', 'project_id'), 'unique' => 0),
						'project_created' => array('column' => array('project_id', 'created'), 'unique' => 0),
						'project_sort_order' => array('column' => array('project_id', 'sort_order'), 'unique' => 0),
					),
					'tableParameters' => array('charset' => 'utf8', 'collate' => 'utf8_general_ci', 'engine' => 'InnoDB'),
				),
				'projects' => array(
					'id' => array('type' => 'integer', 'null' => false, 'default' => null, 'unsigned' => true, 'key' => 'primary'),
					'created' => array('type' => 'timestamp', 'null' => false, 'default' => null),
					'modified' => array('type' => 'timestamp', 'null' => true, 'default' => null),
					'group_id' => array('type' => 'integer', 'null' => false, 'default' => null, 'unsigned' => true, 'key' => 'index'),
					'owner_id' => array('type' => 'integer', 'null' => false, 'default' => null, 'unsigned' => true, 'key' => 'index'),
					'title' => array('type' => 'string', 'null' => false, 'default' => null, 'length' => 1023, 'collate' => 'utf8_general_ci', 'charset' => 'utf8'),
					'descr' => array('type' => 'text', 'null' => true, 'default' => null, 'collate' => 'utf8_general_ci', 'charset' => 'utf8'),
					'deadline' => array('type' => 'timestamp', 'null' => true, 'default' => '0000-00-00 00:00:00', 'key' => 'index'),
					'hidden' => array('type' => 'integer', 'null' => false, 'default' => '0', 'length' => 4, 'unsigned' => true),
					'closed' => array('type' => 'boolean', 'null' => false, 'default' => '0', 'key' => 'index'),
					'deleted' => array('type' => 'boolean', 'null' => false, 'default' => '0'),
					'finance_account_id' => array('type' => 'integer', 'null' => true, 'default' => null, 'unsigned' => false),
					'finance_category_id' => array('type' => 'integer', 'null' => true, 'default' => null, 'unsigned' => false),
					'indexes' => array(
						'PRIMARY' => array('column' => 'id', 'unique' => 1),
						'group_id' => array('column' => 'group_id', 'unique' => 0),
						'owner_id' => array('column' => 'owner_id', 'unique' => 0),
						'closed' => array('column' => 'closed', 'unique' => 0),
						'deadline' => array('column' => 'deadline', 'unique' => 0),
					),
					'tableParameters' => array('charset' => 'utf8', 'collate' => 'utf8_general_ci', 'engine' => 'InnoDB'),
				),
				'sheet_data' => array(
					'sheetid' => array('type' => 'string', 'null' => false, 'key' => 'primary', 'collate' => 'utf8_general_ci', 'charset' => 'utf8'),
					'columnid' => array('type' => 'integer', 'null' => false, 'default' => '0', 'unsigned' => false, 'key' => 'primary'),
					'rowid' => array('type' => 'integer', 'null' => false, 'default' => '0', 'unsigned' => false, 'key' => 'primary'),
					'data' => array('type' => 'string', 'null' => true, 'default' => null, 'collate' => 'utf8_general_ci', 'charset' => 'utf8'),
					'style' => array('type' => 'string', 'null' => true, 'default' => null, 'collate' => 'utf8_general_ci', 'charset' => 'utf8'),
					'parsed' => array('type' => 'string', 'null' => true, 'default' => null, 'collate' => 'utf8_general_ci', 'charset' => 'utf8'),
					'calc' => array('type' => 'string', 'null' => true, 'default' => null, 'collate' => 'utf8_general_ci', 'charset' => 'utf8'),
					'indexes' => array(
						'PRIMARY' => array('column' => array('sheetid', 'columnid', 'rowid'), 'unique' => 1),
					),
					'tableParameters' => array('charset' => 'utf8', 'collate' => 'utf8_general_ci', 'engine' => 'MyISAM'),
				),
				'sheet_header' => array(
					'sheetid' => array('type' => 'string', 'null' => false, 'key' => 'primary', 'collate' => 'utf8_general_ci', 'charset' => 'utf8'),
					'columnid' => array('type' => 'integer', 'null' => false, 'default' => '0', 'unsigned' => false, 'key' => 'primary'),
					'label' => array('type' => 'string', 'null' => true, 'default' => null, 'collate' => 'utf8_general_ci', 'charset' => 'utf8'),
					'width' => array('type' => 'integer', 'null' => true, 'default' => null, 'unsigned' => false),
					'indexes' => array(
						'PRIMARY' => array('column' => array('sheetid', 'columnid'), 'unique' => 1),
					),
					'tableParameters' => array('charset' => 'utf8', 'collate' => 'utf8_general_ci', 'engine' => 'MyISAM'),
				),
				'sheet_sheet' => array(
					'sheetid' => array('type' => 'string', 'null' => false, 'default' => null, 'key' => 'primary', 'collate' => 'utf8_general_ci', 'charset' => 'utf8'),
					'userid' => array('type' => 'integer', 'null' => true, 'default' => null, 'unsigned' => false),
					'name' => array('type' => 'string', 'null' => true, 'default' => null, 'collate' => 'utf8_general_ci', 'charset' => 'utf8'),
					'key' => array('type' => 'string', 'null' => true, 'default' => null, 'collate' => 'utf8_general_ci', 'charset' => 'utf8'),
					'cfg' => array('type' => 'string', 'null' => true, 'default' => null, 'length' => 512, 'collate' => 'utf8_general_ci', 'charset' => 'utf8'),
					'indexes' => array(
						'PRIMARY' => array('column' => 'sheetid', 'unique' => 1),
					),
					'tableParameters' => array('charset' => 'utf8', 'collate' => 'utf8_general_ci', 'engine' => 'MyISAM'),
				),
				'sheet_triggers' => array(
					'id' => array('type' => 'integer', 'null' => false, 'default' => null, 'unsigned' => false, 'key' => 'primary'),
					'sheetid' => array('type' => 'string', 'null' => true, 'default' => null, 'collate' => 'utf8_general_ci', 'charset' => 'utf8'),
					'trigger' => array('type' => 'string', 'null' => true, 'default' => null, 'length' => 10, 'collate' => 'utf8_general_ci', 'charset' => 'utf8'),
					'source' => array('type' => 'string', 'null' => true, 'default' => null, 'length' => 10, 'collate' => 'utf8_general_ci', 'charset' => 'utf8'),
					'indexes' => array(
						'PRIMARY' => array('column' => 'id', 'unique' => 1),
					),
					'tableParameters' => array('charset' => 'utf8', 'collate' => 'utf8_general_ci', 'engine' => 'MyISAM'),
				),
				'skills' => array(
					'id' => array('type' => 'integer', 'null' => false, 'default' => null, 'unsigned' => false, 'key' => 'primary'),
					'rus' => array('type' => 'string', 'null' => true, 'default' => null, 'length' => 127, 'collate' => 'utf8_general_ci', 'charset' => 'utf8'),
					'eng' => array('type' => 'string', 'null' => true, 'default' => null, 'length' => 127, 'collate' => 'utf8_general_ci', 'charset' => 'utf8'),
					'indexes' => array(
						'PRIMARY' => array('column' => 'id', 'unique' => 1),
					),
					'tableParameters' => array('charset' => 'utf8', 'collate' => 'utf8_general_ci', 'engine' => 'InnoDB'),
				),
				'statistic' => array(
					'id' => array('type' => 'integer', 'null' => false, 'default' => null, 'unsigned' => true, 'key' => 'primary'),
					'visitor_id' => array('type' => 'integer', 'null' => false, 'default' => null, 'unsigned' => true),
					'pk' => array('type' => 'integer', 'null' => false, 'default' => null, 'unsigned' => true),
					'type' => array('type' => 'integer', 'null' => false, 'default' => null, 'length' => 3, 'unsigned' => true),
					'created' => array('type' => 'timestamp', 'null' => false, 'default' => null),
					'indexes' => array(
						'PRIMARY' => array('column' => 'id', 'unique' => 1),
					),
					'tableParameters' => array('charset' => 'utf8', 'collate' => 'utf8_general_ci', 'engine' => 'InnoDB'),
				),
				'subprojects' => array(
					'id' => array('type' => 'integer', 'null' => false, 'default' => null, 'unsigned' => true, 'key' => 'primary'),
					'created' => array('type' => 'timestamp', 'null' => false, 'default' => null, 'key' => 'index'),
					'project_id' => array('type' => 'integer', 'null' => false, 'default' => null, 'unsigned' => true, 'key' => 'index'),
					'title' => array('type' => 'string', 'null' => false, 'default' => null, 'length' => 1023, 'collate' => 'utf8_general_ci', 'charset' => 'utf8'),
					'deleted' => array('type' => 'boolean', 'null' => false, 'default' => '0'),
					'indexes' => array(
						'PRIMARY' => array('column' => 'id', 'unique' => 1),
						'project_id' => array('column' => 'project_id', 'unique' => 0),
						'created' => array('column' => 'created', 'unique' => 0),
					),
					'tableParameters' => array('charset' => 'utf8', 'collate' => 'utf8_general_ci', 'engine' => 'InnoDB'),
				),
				'subscriptions' => array(
					'id' => array('type' => 'integer', 'null' => false, 'default' => null, 'unsigned' => false, 'key' => 'primary'),
					'object_id' => array('type' => 'integer', 'null' => false, 'default' => null, 'unsigned' => false),
					'subscriber_id' => array('type' => 'integer', 'null' => false, 'default' => null, 'unsigned' => false),
					'type' => array('type' => 'string', 'null' => false, 'default' => null, 'length' => 16, 'collate' => 'utf8_general_ci', 'charset' => 'utf8'),
					'indexes' => array(
						'PRIMARY' => array('column' => 'id', 'unique' => 1),
					),
					'tableParameters' => array('charset' => 'utf8', 'collate' => 'utf8_general_ci', 'engine' => 'InnoDB'),
				),
				'synonyms' => array(
					'id' => array('type' => 'integer', 'null' => false, 'default' => null, 'unsigned' => false, 'key' => 'primary'),
					'title' => array('type' => 'string', 'null' => false, 'default' => null, 'length' => 1023, 'collate' => 'utf8_general_ci', 'charset' => 'utf8'),
					'variations' => array('type' => 'text', 'null' => false, 'default' => null, 'collate' => 'utf8_general_ci', 'charset' => 'utf8'),
					'indexes' => array(
						'PRIMARY' => array('column' => 'id', 'unique' => 1),
					),
					'tableParameters' => array('charset' => 'utf8', 'collate' => 'utf8_general_ci', 'engine' => 'InnoDB'),
				),
				'tasks' => array(
					'id' => array('type' => 'integer', 'null' => false, 'default' => null, 'unsigned' => true, 'key' => 'primary'),
					'created' => array('type' => 'timestamp', 'null' => false, 'default' => null, 'key' => 'index'),
					'modified' => array('type' => 'timestamp', 'null' => true, 'default' => '0000-00-00 00:00:00'),
					'subproject_id' => array('type' => 'integer', 'null' => false, 'default' => null, 'unsigned' => true, 'key' => 'index'),
					'title' => array('type' => 'string', 'null' => false, 'default' => null, 'length' => 1023, 'collate' => 'utf8_general_ci', 'charset' => 'utf8'),
					'creator_id' => array('type' => 'integer', 'null' => false, 'default' => null, 'unsigned' => true),
					'manager_id' => array('type' => 'integer', 'null' => false, 'default' => null, 'unsigned' => true),
					'user_id' => array('type' => 'integer', 'null' => false, 'default' => null, 'unsigned' => true, 'key' => 'index'),
					'closed' => array('type' => 'boolean', 'null' => false, 'default' => '0'),
					'deadline' => array('type' => 'timestamp', 'null' => true, 'default' => '0000-00-00 00:00:00'),
					'descr' => array('type' => 'text', 'null' => true, 'default' => null, 'collate' => 'utf8_general_ci', 'charset' => 'utf8'),
					'deleted' => array('type' => 'boolean', 'null' => false, 'default' => '0'),
					'indexes' => array(
						'PRIMARY' => array('column' => 'id', 'unique' => 1),
						'subproject_id' => array('column' => 'subproject_id', 'unique' => 0),
						'user_id' => array('column' => 'user_id', 'unique' => 0),
						'created' => array('column' => 'created', 'unique' => 0),
					),
					'tableParameters' => array('charset' => 'utf8', 'collate' => 'utf8_general_ci', 'engine' => 'InnoDB'),
				),
				'temp_documents' => array(
					'id' => array('type' => 'integer', 'null' => false, 'default' => null, 'unsigned' => false, 'key' => 'primary'),
					'user_id' => array('type' => 'integer', 'null' => false, 'default' => null, 'unsigned' => false),
					'type' => array('type' => 'string', 'null' => false, 'default' => null, 'length' => 16, 'collate' => 'utf8_general_ci', 'charset' => 'utf8'),
					'indexes' => array(
						'PRIMARY' => array('column' => 'id', 'unique' => 1),
					),
					'tableParameters' => array('charset' => 'utf8', 'collate' => 'utf8_general_ci', 'engine' => 'InnoDB'),
				),
				'user_achievements' => array(
					'id' => array('type' => 'integer', 'null' => false, 'default' => null, 'unsigned' => true, 'key' => 'primary'),
					'created' => array('type' => 'timestamp', 'null' => false, 'default' => null),
					'user_id' => array('type' => 'integer', 'null' => false, 'default' => null, 'unsigned' => true, 'key' => 'index'),
					'title' => array('type' => 'text', 'null' => true, 'default' => null, 'collate' => 'utf8_general_ci', 'charset' => 'utf8'),
					'url' => array('type' => 'string', 'null' => true, 'default' => null, 'length' => 1023, 'collate' => 'utf8_general_ci', 'charset' => 'utf8'),
					'indexes' => array(
						'PRIMARY' => array('column' => 'id', 'unique' => 1),
						'user_id' => array('column' => 'user_id', 'unique' => 0),
					),
					'tableParameters' => array('charset' => 'utf8', 'collate' => 'utf8_general_ci', 'engine' => 'InnoDB'),
				),
				'user_event_shares' => array(
					'id' => array('type' => 'integer', 'null' => false, 'default' => null, 'unsigned' => false, 'key' => 'primary'),
					'user_id' => array('type' => 'integer', 'null' => false, 'default' => null, 'unsigned' => false),
					'user_event_id' => array('type' => 'integer', 'null' => false, 'default' => null, 'unsigned' => false),
					'acceptance' => array('type' => 'integer', 'null' => false, 'default' => '0', 'length' => 1, 'unsigned' => false),
					'indexes' => array(
						'PRIMARY' => array('column' => 'id', 'unique' => 1),
					),
					'tableParameters' => array('charset' => 'utf8', 'collate' => 'utf8_general_ci', 'engine' => 'InnoDB'),
				),
				'user_events' => array(
					'id' => array('type' => 'integer', 'null' => false, 'default' => null, 'unsigned' => true, 'key' => 'primary'),
					'created' => array('type' => 'timestamp', 'null' => false, 'default' => null, 'key' => 'index'),
					'event_time' => array('type' => 'timestamp', 'null' => false, 'default' => '0000-00-00 00:00:00'),
					'event_end_time' => array('type' => 'timestamp', 'null' => false, 'default' => '0000-00-00 00:00:00'),
					'previous_event_time' => array('type' => 'timestamp', 'null' => false, 'default' => '0000-00-00 00:00:00'),
					'type' => array('type' => 'string', 'null' => false, 'default' => null, 'length' => 16, 'collate' => 'utf8_general_ci', 'charset' => 'utf8'),
					'user_id' => array('type' => 'integer', 'null' => false, 'default' => null, 'unsigned' => true, 'key' => 'index'),
					'recipient_id' => array('type' => 'string', 'null' => true, 'default' => null, 'collate' => 'utf8_general_ci', 'charset' => 'utf8'),
					'title' => array('type' => 'string', 'null' => false, 'default' => null, 'length' => 1023, 'collate' => 'utf8_general_ci', 'charset' => 'utf8'),
					'descr' => array('type' => 'text', 'null' => true, 'default' => null, 'collate' => 'utf8_general_ci', 'charset' => 'utf8'),
					'shared' => array('type' => 'boolean', 'null' => false, 'default' => '0'),
					'is_delayed' => array('type' => 'boolean', 'null' => false, 'default' => '0', 'comment' => 'Отложенное событие'),
					'category' => array('type' => 'boolean', 'null' => false, 'default' => '0', 'comment' => 'Категоря события. 0 - работа, 1 - личое. Изначально берётся при создании события, исходя из типа события.'),
					'object_type' => array('type' => 'string', 'null' => true, 'default' => null, 'length' => 16, 'collate' => 'utf8_general_ci', 'charset' => 'utf8'),
					'object_id' => array('type' => 'integer', 'null' => true, 'default' => null, 'unsigned' => false),
					'place_name' => array('type' => 'string', 'null' => true, 'default' => null, 'length' => 1023, 'collate' => 'utf8_general_ci', 'charset' => 'utf8'),
					'place_coords' => array('type' => 'string', 'null' => true, 'default' => null, 'length' => 63, 'collate' => 'utf8_general_ci', 'charset' => 'utf8'),
					'finance_operation_id' => array('type' => 'integer', 'null' => true, 'default' => null, 'unsigned' => false),
					'indexes' => array(
						'PRIMARY' => array('column' => 'id', 'unique' => 1),
						'user_id_event_time' => array('column' => array('user_id', 'event_time'), 'unique' => 0),
						'created' => array('column' => 'created', 'unique' => 0),
					),
					'tableParameters' => array('charset' => 'utf8', 'collate' => 'utf8_general_ci', 'engine' => 'InnoDB'),
				),
				'users' => array(
					'id' => array('type' => 'integer', 'null' => false, 'default' => null, 'unsigned' => true, 'key' => 'primary'),
					'fbid' => array('type' => 'string', 'null' => true, 'default' => null, 'length' => 32, 'collate' => 'utf8_general_ci', 'charset' => 'utf8'),
					'created' => array('type' => 'timestamp', 'null' => false, 'default' => null, 'key' => 'index'),
					'modified' => array('type' => 'timestamp', 'null' => true, 'default' => '0000-00-00 00:00:00'),
					'is_admin' => array('type' => 'integer', 'null' => false, 'default' => '0', 'unsigned' => true, 'key' => 'index'),
					'is_confirmed' => array('type' => 'boolean', 'null' => false, 'default' => '0'),
					'is_deleted' => array('type' => 'boolean', 'null' => false, 'default' => '0'),
					'username' => array('type' => 'string', 'null' => false, 'default' => null, 'length' => 50, 'key' => 'index', 'collate' => 'utf8_general_ci', 'charset' => 'utf8'),
					'password' => array('type' => 'string', 'null' => false, 'default' => null, 'length' => 50, 'collate' => 'utf8_general_ci', 'charset' => 'utf8'),
					'full_name' => array('type' => 'string', 'null' => true, 'default' => null, 'length' => 1023, 'collate' => 'utf8_general_ci', 'charset' => 'utf8'),
					'profile_url' => array('type' => 'string', 'null' => true, 'default' => null, 'length' => 32, 'collate' => 'utf8_general_ci', 'charset' => 'utf8'),
					'video_url' => array('type' => 'string', 'null' => true, 'default' => null, 'length' => 1023, 'collate' => 'utf8_general_ci', 'charset' => 'utf8'),
					'video_id' => array('type' => 'string', 'null' => true, 'default' => null, 'length' => 1023, 'collate' => 'utf8_general_ci', 'charset' => 'utf8'),
					'skills' => array('type' => 'text', 'null' => true, 'default' => null, 'collate' => 'utf8_general_ci', 'charset' => 'utf8'),
					'birthday' => array('type' => 'date', 'null' => true, 'default' => null),
					'lang' => array('type' => 'string', 'null' => true, 'default' => 'eng', 'length' => 3, 'collate' => 'utf8_general_ci', 'charset' => 'utf8'),
					'phone' => array('type' => 'string', 'null' => true, 'default' => null, 'length' => 1023, 'collate' => 'utf8_general_ci', 'charset' => 'utf8'),
					'live_place' => array('type' => 'text', 'null' => true, 'default' => null, 'collate' => 'utf8_general_ci', 'charset' => 'utf8'),
					'live_address' => array('type' => 'text', 'null' => true, 'default' => null, 'collate' => 'utf8_general_ci', 'charset' => 'utf8'),
					'university' => array('type' => 'string', 'null' => true, 'default' => null, 'length' => 1023, 'collate' => 'utf8_general_ci', 'charset' => 'utf8'),
					'speciality' => array('type' => 'string', 'null' => true, 'default' => null, 'length' => 1023, 'collate' => 'utf8_general_ci', 'charset' => 'utf8'),
					'live_country' => array('type' => 'string', 'null' => true, 'default' => null, 'length' => 1023, 'collate' => 'utf8_general_ci', 'charset' => 'utf8'),
					'timezone' => array('type' => 'string', 'null' => true, 'default' => null, 'length' => 50, 'collate' => 'utf8_general_ci', 'charset' => 'utf8'),
					'lat' => array('type' => 'decimal', 'null' => true, 'default' => null, 'length' => '10,8', 'unsigned' => false),
					'lng' => array('type' => 'decimal', 'null' => true, 'default' => null, 'length' => '11,8', 'unsigned' => false),
					'balance' => array('type' => 'float', 'null' => false, 'default' => '0.00', 'length' => '9,2', 'unsigned' => true),
					'news_update' => array('type' => 'timestamp', 'null' => false, 'default' => '0000-00-00 00:00:00'),
					'last_update' => array('type' => 'timestamp', 'null' => false, 'default' => '0000-00-00 00:00:00'),
					'indexes' => array(
						'PRIMARY' => array('column' => 'id', 'unique' => 1),
						'username' => array('column' => 'username', 'unique' => 0),
						'user_group_id' => array('column' => 'is_admin', 'unique' => 0),
						'created' => array('column' => 'created', 'unique' => 0),
					),
					'tableParameters' => array('charset' => 'utf8', 'collate' => 'utf8_general_ci', 'engine' => 'InnoDB'),
				),
				'vacancy_response' => array(
					'id' => array('type' => 'integer', 'null' => false, 'default' => null, 'unsigned' => false, 'key' => 'primary'),
					'user_id' => array('type' => 'integer', 'null' => false, 'default' => null, 'unsigned' => false),
					'vacancy_id' => array('type' => 'integer', 'null' => false, 'default' => null, 'unsigned' => false),
					'approve' => array('type' => 'integer', 'null' => false, 'default' => null, 'length' => 2, 'unsigned' => false),
					'created' => array('type' => 'timestamp', 'null' => false, 'default' => null),
					'modified' => array('type' => 'timestamp', 'null' => true, 'default' => '0000-00-00 00:00:00'),
					'indexes' => array(
						'PRIMARY' => array('column' => 'id', 'unique' => 1),
					),
					'tableParameters' => array('charset' => 'latin1', 'collate' => 'latin1_swedish_ci', 'engine' => 'InnoDB'),
				),
			),
		),
		'down' => array(
			'drop_table' => array(
				'api_accesses', 'article_events', 'articles', 'balance_operations', 'chat_contacts', 'chat_events', 'chat_members', 'chat_messages', 'chat_rooms', 'cloud', 'contractors', 'countries',  'crm_tasks', 'faqs', 'favourite_lists', 'favourite_users', 'finance_account', 'finance_budget', 'finance_calendar', 'finance_category', 'finance_goals', 'finance_operation', 'finance_operation_has_category', 'finance_project', 'finance_share', 'group_achievements', 'group_addresses', 'group_categories', 'group_members', 'group_vacancy', 'group_videos', 'groups', 'invest_category', 'invest_project', 'invest_reward', 'invest_sponsor', 'invest_video', 'media', 'notes', 'order_products', 'order_reports', 'order_types', 'orders', 'product_types', 'products', 'project_events', 'project_finances', 'project_members', 'projects', 'sheet_data', 'sheet_header', 'sheet_sheet', 'sheet_triggers', 'skills', 'statistic', 'subprojects', 'subscriptions', 'synonyms', 'tasks', 'temp_documents', 'user_achievements', 'user_event_shares', 'user_events', 'users', 'vacancy_response'
			),
		),
	);

/**
 * Before migration callback
 *
 * @param string $direction Direction of migration process (up or down)
 * @return bool Should process continue
 */
	public function before($direction) {
		return true;
	}

/**
 * After migration callback
 *
 * @param string $direction Direction of migration process (up or down)
 * @return bool Should process continue
 */
	public function after($direction) {
		return true;
	}
}
